# this file defines behavior for the 'ganglia-nodes' class of nodes

- name: install gmond
  action: yum pkg=ganglia-gmond state=installed
  tags:
    - packages

- name: configure gmond
  action: template src=monitoring/templates/etc/ganglia/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond

- name: ensure ganglia is running
  action: service name=gmond state=running
