---
- hosts:
  - cloudera-manager
  - cluster
  user: root
  sudo: yes
  vars_files:
  - vars/common.yml
  tasks:
  - include: cloudera-manager/tasks/common.yml
  handlers:
  - include: cloudera-manager/handlers/main.yml

- hosts: cloudera-manager
  user: root
  sudo: yes
  vars_files:
  - vars/common.yml
  tasks:
  - include: cloudera-manager/tasks/server.yml
  handlers:
  - include: cloudera-manager/handlers/main.yml

- hosts: cluster
  user: root
  sudo: yes
  vars_files:
  - vars/common.yml
  tasks:
  - include: cloudera-manager/tasks/agents.yml
  handlers:
  - include: cloudera-manager/handlers/main.yml
