- name: restart gmetad
  action: service name=gmetad state=restarted

- name: restart gmond
  action: service name=gmond state=restarted

- name: restart httpd
  action: service name=httpd state=restarted
